apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api-demo
  template:
    metadata:
      labels:
        app: flask-api-demo
    spec:
      containers:
      - name: flask-api-demo
        image: flask-api-demo
        ports:
        - containerPort: 8000
        env:
        - name: VERY_VERY_SECRET
          valueFrom:
            secretKeyRef:
              name: very-secret-secret
              key: VERY_VERY_SECRET
